version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - GITHUB_OWNER=${GITHUB_OWNER}
      - GITHUB_REPO=${GITHUB_REPO}
      - SCREENSHOT_STORAGE_PATH=/app/data/screenshots
      - POLL_INTERVAL_MINUTES=${POLL_INTERVAL_MINUTES:-5}
    volumes:
      - screenshot_data:/app/data/screenshots
      - temp_data:/app/temp

volumes:
  screenshot_data:
  temp_data:
